name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Type "DEPLOY" to confirm production deployment'
        required: true
        type: string
        default: ""

env:
  AWS_REGION: us-east-1

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Bootstrap CDK (if needed)
        run: npx cdk bootstrap --require-approval never
        continue-on-error: true

      - name: Synthesize CDK
        run: npx cdk synth

      - name: Validate deployment confirmation
        run: |
          if [ "${{ github.event.inputs.confirm_deploy }}" != "DEPLOY" ]; then
            echo "❌ Deployment cancelled. Please type 'DEPLOY' to confirm."
            exit 1
          fi
          echo "✅ Deployment confirmed. Proceeding to production..."

      - name: Deploy to production
        run: npx cdk deploy --require-approval never --context stage=prod

      - name: Deployment complete
        run: |
          echo "🎉 Production deployment completed successfully!"
          echo "Stack: prod-legal-ai-infra-stack"
          echo "Region: ${{ env.AWS_REGION }}"
